"《" @keyword
"》" @keyword
(role) @type
;;(song_title) @variable
(creator_name) @constant.builtin
(parts) @variable.parameter
(cv_conj) @variable.parameter
(comment) @comment
"DISC" @keyword
(ERROR) @tag
